name: HTML Preview
on: [check_suite]

jobs:
  html_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HTML Preview
        uses: pavi2410/html-preview-action@v1a
